# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv-{{ checksum "requirements-dev.txt" }}
            - venv-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tensorflow==1.13.1            
            pip install -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: venv-{{ checksum "requirements-dev.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -e .
            export CUDA_VISIBLE_DEVICES=''
            pytest tests/ --cov=pinn
            codecov --token=ef4ee5ca-5df3-4535-8b9e-034fdf81495d
